In [4]:
import numpy as np

X = np.array([[2, 3],
              [5, 4],
              [7, 8],
              [9, 6],
              [4, 5],
              [8, 1]])
y = np.array([0, 1, 1, 1, 0, 1])  

class Node:
    def __init__(self, gini, label):
        self.gini = gini
        self.label = label
        self.feature = None
        self.threshold = None
        self.left = None
        self.right = None

def gini_impurity(y):
    _, counts = np.unique(y, return_counts=True)
    proportions = counts / len(y)
    impurity = 1 - np.sum(proportions ** 2)
    return impurity

def split(X, y, feature_index, threshold):
    left_mask = X[:, feature_index] <= threshold
    right_mask = ~left_mask
    return y[left_mask], y[right_mask]

def build_tree(X, y, depth=0, max_depth=None):
    if depth == max_depth or np.unique(y).size == 1:
        label = np.bincount(y).argmax()
        return Node(gini_impurity(y), label)

    best_gini = np.inf
    best_feature = None
    best_threshold = None
    for feature_index in range(X.shape[1]):
        thresholds = np.unique(X[:, feature_index])
        for threshold in thresholds:
            left_y, right_y = split(X, y, feature_index, threshold)
            gini = len(left_y) * gini_impurity(left_y) + len(right_y) * gini_impurity(right_y)
            if gini < best_gini:
                best_gini = gini
                best_feature = feature_index
                best_threshold = threshold

    if best_feature is None:
        label = np.bincount(y).argmax()
        return Node(gini_impurity(y), label)

    left_y, right_y = split(X, y, best_feature, best_threshold)
    left_node = build_tree(X, left_y, depth + 1, max_depth)
    right_node = build_tree(X, right_y, depth + 1, max_depth)
    node = Node(best_gini, None)
    node.feature = best_feature
    node.threshold = best_threshold
    node.left = left_node
    node.right = right_node
    return node

def predict_one(node, x):
    if node.label is not None:
        return node.label
    if x[node.feature] <= node.threshold:
        return predict_one(node.left, x)
    else:
        return predict_one(node.right, x)

def predict(root, X):
    return np.array([predict_one(root, x) for x in X])

# Build the decision tree
root = build_tree(X, y, max_depth=3)

test_samples = np.array([[6, 4], [3,2]])
predictions = predict(root, test_samples)
for i, prediction in enumerate(predictions):
    print(f"Sample {i+1}: Predicted Class {prediction}")


Sample 1: Predicted Class 1
Sample 2: Predicted Class 0


In [9]:
import numpy as np

# Sample dataset: features and their corresponding target values
X = np.array([[2],
              [5],
              [7],
              [9],
              [4],
              [8]])
y = np.array([10, 20, 25, 30, 15, 22])  # Target values

class Node:
    def __init__(self, value):
        self.value = value
        self.feature = None
        self.threshold = None
        self.left = None
        self.right = None

def mse(y):
    mean = np.mean(y)
    error = np.mean((y - mean) ** 2)
    return error

def split(X, y, feature_index, threshold):
    left_mask = X[:, feature_index] <= threshold
    right_mask = ~left_mask
    return X[left_mask], X[right_mask], y[left_mask], y[right_mask]

def build_tree(X, y, depth=0, max_depth=None):
    if depth == max_depth or len(np.unique(y)) == 1:
        value = np.mean(y)
        return Node(value)

    best_mse = np.inf
    best_feature = None
    best_threshold = None
    for feature_index in range(X.shape[1]):
        thresholds = np.unique(X[:, feature_index])
        for threshold in thresholds:
            left_X, right_X, left_y, right_y = split(X, y, feature_index, threshold)
            mse_value = len(left_y) * mse(left_y) + len(right_y) * mse(right_y)
            if mse_value < best_mse:
                best_mse = mse_value
                best_feature = feature_index
                best_threshold = threshold

    left_X, right_X, left_y, right_y = split(X, y, best_feature, best_threshold)
    left_node = build_tree(left_X, left_y, depth + 1, max_depth)
    right_node = build_tree(right_X, right_y, depth + 1, max_depth)
    node = Node(None)
    node.feature = best_feature
    node.threshold = best_threshold
    node.left = left_node
    node.right = right_node
    return node

def predict_one(node, x):
    if node.value is not None:
        return node.value
    if x[node.feature] <= node.threshold:
        return predict_one(node.left, x)
    else:
        return predict_one(node.right, x)

def predict(root, X):
    return np.array([predict_one(root, x) for x in X])

# Build the decision tree
root = build_tree(X, y, max_depth=3)

# Predict and print results
test_samples = np.array([[6], [3]])
predictions = predict(root, test_samples)
for i, prediction in enumerate(predictions):
    print(f"Sample {i+1}: Predicted Value {prediction}")


Sample 1: Predicted Value 23.5
Sample 2: Predicted Value 15.0


In [1]:
from sklearn.tree import DecisionTreeClassifier

In [2]:
from sklearn.tree import DecisionTreeRegressor

In [2]:
from sklearn.tree import DecisionTreeClassifier

In [3]:
import numpy as np

In [4]:
X = np.array([[2, 3],
              [5, 4],
              [7, 8],
              [9, 6],
              [4, 5],
              [8, 1]])
y = np.array([0, 1, 1, 1, 0, 1])

In [5]:
X

array([[2, 3],
       [5, 4],
       [7, 8],
       [9, 6],
       [4, 5],
       [8, 1]])

In [6]:
y

array([0, 1, 1, 1, 0, 1])

In [7]:
dt = DecisionTreeClassifier()

In [8]:
dt.fit(X,y)

DecisionTreeClassifier()

In [9]:
y_pred = dt.predict([[1,2]])

In [10]:
y_pred

array([0])

In [11]:
X = np.array([[2, 3],
              [5, 4],
              [7, 8],
              [9, 6],
              [4, 5],
              [8, 1]])
y = np.array([1.4, 1.7, 2.6, 4.3, 5.3, 5.4])

In [12]:
from sklearn.tree import DecisionTreeRegressor

In [13]:
dr =  DecisionTreeRegressor()

In [15]:
dr.fit(X,y)

DecisionTreeRegressor()

In [16]:
y_pred = dr.predict([[1,2]])

In [17]:
y_pred

array([1.4])