In [1]:
import numpy as np

def standardize_data(X):
    mean_vals = np.mean(X, axis=0)
    std_devs = np.std(X, axis=0)
    standardized_data = (X - mean_vals) / std_devs
    return standardized_data

def calculate_covariance_matrix(X):
    covariance_matrix = np.cov(X, rowvar=False)
    return covariance_matrix

def calculate_eigenvalues_and_eigenvectors(covariance_matrix):
    eigenvalues, eigenvectors = np.linalg.eig(covariance_matrix)
    return eigenvalues, eigenvectors

def pca(X, num_components):
    X_standardized = standardize_data(X)
    covariance_matrix = calculate_covariance_matrix(X_standardized)
    eigenvalues, eigenvectors = calculate_eigenvalues_and_eigenvectors(covariance_matrix)
    sorted_indices = np.argsort(eigenvalues)[::-1]
    top_indices = sorted_indices[:num_components]
    top_eigenvectors = eigenvectors[:, top_indices]
    new_features = np.dot(X_standardized, top_eigenvectors)
    return new_features

data = np.array([
    [63, 127],
    [64, 121],
    [66, 142],
    [69, 157],
    [69, 162],
    [71, 156],
    [72, 169],
    [74, 175],
    [75, 182]
])

num_components = 1  
result = pca(data, num_components)

print("Original Data:\n", data)
print("\nReduced Dimensional Space:\n", result)

Original Data:
 [[ 63 127]
 [ 64 121]
 [ 66 142]
 [ 69 157]
 [ 69 162]
 [ 71 156]
 [ 72 169]
 [ 74 175]
 [ 75 182]]

Reduced Dimensional Space:
 [[-2.09165142]
 [-2.13016715]
 [-1.02158638]
 [ 0.04847865]
 [ 0.22811687]
 [ 0.36665127]
 [ 1.01076076]
 [ 1.58042688]
 [ 2.00897051]]


In [2]:
import numpy as np

class PCA:
    def __init__(self, num_components):
        self.num_components = num_components
        self.mean_vals = None
        self.std_devs = None
        self.top_eigenvectors = None

    def standardize_data(self, X):
        self.mean_vals = np.mean(X, axis=0)
        self.std_devs = np.std(X, axis=0)
        standardized_data = (X - self.mean_vals) / self.std_devs
        return standardized_data

    def calculate_covariance_matrix(self, X):
        covariance_matrix = np.cov(X, rowvar=False)
        return covariance_matrix

    def calculate_eigenvalues_and_eigenvectors(self, covariance_matrix):
        eigenvalues, eigenvectors = np.linalg.eig(covariance_matrix)
        return eigenvalues, eigenvectors

    def fit_transform(self, X):
        X_standardized = self.standardize_data(X)
        covariance_matrix = self.calculate_covariance_matrix(X_standardized)
        eigenvalues, eigenvectors = self.calculate_eigenvalues_and_eigenvectors(covariance_matrix)
        sorted_indices = np.argsort(eigenvalues)[::-1]
        top_indices = sorted_indices[:self.num_components]
        self.top_eigenvectors = eigenvectors[:, top_indices]
        new_features = np.dot(X_standardized, self.top_eigenvectors)
        return new_features

data = np.array([
    [63, 127],
    [64, 121],
    [66, 142],
    [69, 157],
    [69, 162],
    [71, 156],
    [72, 169],
    [74, 175],
    [75, 182]
])

num_components = 1

pca = PCA(num_components=num_components)
result = pca.fit_transform(data)

print("Original Data:\n", data)
print("\nReduced Dimensional Space:\n", result)

Original Data:
 [[ 63 127]
 [ 64 121]
 [ 66 142]
 [ 69 157]
 [ 69 162]
 [ 71 156]
 [ 72 169]
 [ 74 175]
 [ 75 182]]

Reduced Dimensional Space:
 [[-2.09165142]
 [-2.13016715]
 [-1.02158638]
 [ 0.04847865]
 [ 0.22811687]
 [ 0.36665127]
 [ 1.01076076]
 [ 1.58042688]
 [ 2.00897051]]


In [3]:
import numpy as np
from sklearn.decomposition import PCA

data = np.array([
    [63, 127],
    [64, 121],
    [66, 142],
    [69, 157],
    [69, 162],
    [71, 156],
    [72, 169],
    [74, 175],
    [75, 182]
])

num_components = 1
pca = PCA(n_components=num_components)

result = pca.fit_transform(data)

print("Original Data:\n", data)
print("\nReduced Dimensional Space:\n", result)

Original Data:
 [[ 63 127]
 [ 64 121]
 [ 66 142]
 [ 69 157]
 [ 69 162]
 [ 71 156]
 [ 72 169]
 [ 74 175]
 [ 75 182]]

Reduced Dimensional Space:
 [[ 28.23835161]
 [ 33.93258253]
 [ 12.94137114]
 [ -2.35560934]
 [ -7.26162043]
 [ -1.76037191]
 [-14.70898315]
 [-20.98216126]
 [-28.04355919]]


In [4]:
import numpy as np

class PCA:
    def __init__(self, num_components):
        self.num_components = num_components
        self.mean_vals = None
        self.std_devs = None
        self.top_eigenvectors = None

    def standardize_data(self, X):
        self.mean_vals = np.mean(X, axis=0)
        self.std_devs = np.std(X, axis=0)
        standardized_data = (X - self.mean_vals) / self.std_devs
        return standardized_data

    def calculate_covariance_matrix(self, X):
        covariance_matrix = np.cov(X, rowvar=False)
        return covariance_matrix

    def calculate_eigenvalues_and_eigenvectors(self, covariance_matrix):
        eigenvalues, eigenvectors = np.linalg.eig(covariance_matrix)
        return eigenvalues, eigenvectors

    def fit_transform(self, X):
        X_standardized = self.standardize_data(X)
        covariance_matrix = self.calculate_covariance_matrix(X_standardized)
        eigenvalues, eigenvectors = self.calculate_eigenvalues_and_eigenvectors(covariance_matrix)
        sorted_indices = np.argsort(eigenvalues)[::-1]
        top_indices = sorted_indices[:self.num_components]
        self.top_eigenvectors = eigenvectors[:, top_indices]
        new_features = np.dot(X_standardized, self.top_eigenvectors)
        return new_features

# Given data
height = np.array([63, 64, 66, 69, 69, 71, 72, 74, 75])
weight = np.array([127, 121, 142, 157, 162, 156, 169, 175, 182])

# Combine height and weight into a 2D array
data = np.column_stack((height, weight))

# Number of components to retain
num_components = 1

# Apply PCA
pca = PCA(num_components=num_components)
result = pca.fit_transform(data)

# Display the original and reduced-dimensional data
print("Original Data:")
print("Height:", height)
print("Weight:", weight)
print("\nReduced Dimensional Space:\n", result)


Original Data:
Height: [63 64 66 69 69 71 72 74 75]
Weight: [127 121 142 157 162 156 169 175 182]

Reduced Dimensional Space:
 [[-2.09165142]
 [-2.13016715]
 [-1.02158638]
 [ 0.04847865]
 [ 0.22811687]
 [ 0.36665127]
 [ 1.01076076]
 [ 1.58042688]
 [ 2.00897051]]
